package com.miaoshaProject.dao;

import com.miaoshaProject.dataobject.UserPassWordDO;

public interface UserPassWordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 28 15:35:06 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 28 15:35:06 CST 2020
     */
    int insert(UserPassWordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 28 15:35:06 CST 2020
     */
    int insertSelective(UserPassWordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 28 15:35:06 CST 2020
     */
    UserPassWordDO selectByPrimaryKey(Integer id);

    UserPassWordDO selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 28 15:35:06 CST 2020
     */
    int updateByPrimaryKeySelective(UserPassWordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 28 15:35:06 CST 2020
     */
    int updateByPrimaryKey(UserPassWordDO record);
}